### ISSUE TITLE
Make network configuration of factory vm configurable

### ISSUE THREAD

**Issue by peterschen** [BenjaminArmstrong/Hyper-V-PowerShell#11]
In some scenarios you might want to have the ability to configure the network configuration as internet egress is only available for certain networks. An option should be added which enables a static configuration of the deployed factory vm.

**Comment by BenjaminArmstrong** [comment]
Yup, definitely want to enable this.

**Comment by grantemsley** [comment]
I am working on something for this.  Just need to test it first.

**Comment by BenjaminArmstrong** [comment]
Thanks Grant!
